
# development

FROM python:3.11-alpine

WORKDIR /app

# Install the Python dependencies
COPY ./requirements.txt .
RUN pip install -r requirements.txt

COPY ./src .



ENTRYPOINT ["python"]
CMD ["server.py"]